services:
  kneecap:
    image: ghcr.io/tummyslyunopened/kneecap-backend:canary
    volumes:
      - kneecap_db:/kneecap_db/
      - kneecap_media:/kneecap_media/
    environment:
      PROD: $PROD
      SECRET_KEY: $SECRET_KEY
      SITE_URL: $SITE_URL
      MEDIA_ROOT: $MEDIA_ROOT
      DB_PATH: $DB_PATH
    networks:
      - nginx_dmz

volumes:
  kneecap_db:
    external: true
  kneecap_media:
    external: true

networks:
  nginx_dmz:
    external: true