# Generated by Django 5.2 on 2025-06-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minute",
            name="playback_time",
            field=models.IntegerField(default=0),
        ),
    ]
