# Generated by Django 5.2 on 2025-05-01 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscriptions", "0003_episode_transcript_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_time", models.CharField(max_length=100)),
                ("end_time", models.CharField(max_length=100)),
                ("text", models.CharField(max_length=1000)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_segments",
                        to="subscriptions.episode",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
