# Generated by Django 5.1.4 on 2024-12-27 01:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('link', models.URLField()),
                ('description', models.TextField(default='')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rss_feed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mirror', to='rss.rssfeed')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('media', models.URLField(blank=True, null=True)),
                ('played', models.BooleanField(default=False)),
                ('current_playback_time', models.DurationField(blank=True, null=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rss_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='rss.rssfeed')),
            ],
        ),
    ]
