# Generated by Django 5.1.4 on 2024-12-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='podcast_url',
            field=models.URLField(blank=True),
        ),
    ]
