# Generated by Django 5.1.4 on 2024-12-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_episode_podcast_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='current_playback_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='episode',
            name='played',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='episode',
            name='podcast_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
