# Generated by Django 5.1.4 on 2024-12-27 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_episode_local_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='local_path',
        ),
    ]
