# Generated by Django 5.1.4 on 2024-12-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_episode_current_playback_time_episode_downloaded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
