# Generated by Django 5.1.4 on 2024-12-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0004_alter_rssfeed_description_alter_rssfeed_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
