# Generated by Django 5.1.4 on 2024-12-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0005_alter_rssfeed_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='downloaded',
        ),
    ]
