# Generated by Django 5.1.4 on 2024-12-27 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0005_rssfeed_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrippedMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripped_content', models.TextField(help_text='RSS content with only tracked parameters')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('feed_mirror', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripped_mirror', to='rss.feedmirror')),
            ],
            options={
                'verbose_name': 'Stripped Mirror',
                'verbose_name_plural': 'Stripped Mirrors',
            },
        ),
    ]
