# Generated by Django 5.1.4 on 2024-12-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0006_remove_episode_downloaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
