# Generated by Django 5.1.4 on 2024-12-25 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0007_alter_rssfeed_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='link',
        ),
    ]
