# Generated by Django 5.1.4 on 2024-12-25 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0009_alter_rssfeed_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='podcast_url',
            new_name='media',
        ),
    ]
