# Generated by Django 5.2 on 2025-04-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalThrottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("last_called", models.DateTimeField(blank=True, null=True)),
                ("interval_seconds", models.IntegerField()),
            ],
        ),
    ]
