# Generated by Django 5.2 on 2025-04-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="scheduled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
