# Generated by Django 5.2 on 2025-04-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="last_media_download",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="media_download_interval",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
