# Generated by Django 5.1.4 on 2025-01-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="recent_episode_pub_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
