# Generated by Django 5.2 on 2025-05-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_subscription_last_media_download_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="transcript_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
