# Generated by Django 5.1.4 on 2025-01-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_event_episode_hidden_episodewatchevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chronological", models.BooleanField(default=False)),
                ("view_hidden", models.BooleanField(default=False)),
                ("cutoff_days", models.IntegerField(default=7)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
