# Generated by Django 5.2 on 2025-05-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_episode_low_quality_audio_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="autoplay_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
