# Generated by Django 5.1.4 on 2025-04-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_feed"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="queued_for_download",
            field=models.BooleanField(default=False),
        ),
    ]
