# Generated by Django 5.1.4 on 2025-04-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_episode_queued_for_download"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
