# Generated by Django 5.2 on 2025-05-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_feed_autoplay_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="autoplay_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
