# Generated by Django 5.2 on 2025-05-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_alter_feed_autoplay_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="has_local_audio",
            field=models.BooleanField(
                default=False,
                help_text="Filter by whether episodes have a local audio file (leave blank for any)",
                verbose_name="Has Local Audio",
            ),
        ),
        migrations.AddField(
            model_name="feed",
            name="has_transcript",
            field=models.BooleanField(
                default=False,
                help_text="Filter by whether episodes have a transcript (leave blank for any)",
                verbose_name="Has Transcript",
            ),
        ),
        migrations.AddField(
            model_name="feed",
            name="min_duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Only show episodes longer than this duration in seconds",
                null=True,
                verbose_name="Minimum Duration (seconds)",
            ),
        ),
    ]
