# Generated by Django 5.1.4 on 2025-04-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_subscription_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="duration",
        ),
        migrations.AddField(
            model_name="episode",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
