# Generated by Django 5.2 on 2025-05-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_feed_has_local_audio_feed_has_transcript_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feed",
            name="has_local_audio",
        ),
        migrations.AddField(
            model_name="feed",
            name="has_audio",
            field=models.BooleanField(
                default=False,
                help_text="Filter by whether episodes have a local audio file (leave blank for any)",
                verbose_name="Has Audio",
            ),
        ),
    ]
