# Generated by Django 5.1.4 on 2025-04-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_remove_subscription_duration_episode_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="last_refresh",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
