# Generated by Django 5.1.4 on 2025-04-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_subscription_last_refresh"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="playback_time",
            field=models.IntegerField(default=0),
        ),
    ]
